[package]
name = "burncloud-client-log"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["desktop"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
