[package]
name = "burncloud-router"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
reqwest = { workspace = true, features = ["stream", "json"] }
anyhow = { workspace = true }
http-body-util = "0.1"

burncloud-database = { workspace = true }
burncloud-database-router = { workspace = true }
burncloud-router-aws = { workspace = true }

axum = { version = "0.7", features = ["macros"] }
tower-http = { version = "0.5", features = ["trace", "cors"] }
tracing = "0.1"

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }

[[example]]
name = "setup_test_auth"
path = "examples/setup_test_auth.rs"

[[example]]
name = "configure_apikey_test"
path = "examples/configure_apikey_test.rs"
