[package]
name = "burncloud-service-models"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-database-models.workspace = true
burncloud-database.workspace = true
burncloud-service-ip.workspace = true
burncloud-service-setting.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
