[package]
name = "burncloud-service-ip"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-service-setting = { path = "../service-setting" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
