[package]
name = "burncloud-client-users"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus.workspace = true
burncloud-client-shared = { path = "../client-shared" }
burncloud-common.workspace = true
