[package]
name = "burncloud-service-user"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-database-user.workspace = true
burncloud-database.workspace = true
burncloud-common.workspace = true
bcrypt.workspace = true
uuid.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio.workspace = true
anyhow.workspace = true
