[package]
name = "burncloud-client-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus.workspace = true
burncloud-client-shared.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
