[package]
name = "burncloud-client-models"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus.workspace = true
dioxus-router.workspace = true
serde_json.workspace = true
chrono.workspace = true
