[package]
name = "burncloud-service"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-service-ip.workspace = true
burncloud-service-models.workspace = true
burncloud-service-monitor.workspace = true
