[package]
name = "burncloud-database-user"
version = "0.1.0"
edition = "2021"

[dependencies]
burncloud-database.workspace = true
sqlx.workspace = true
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
